baseurl = "http://www.alexanderbartels.com/swproxy-www/"
languageCode = "en-us"
title = "swproxy | the library to write service worker"
theme = "mdl"
MetaDataFormat = "yaml"
[permalinks]
	home = "/:home/"
	mods = "/:mods/"
[params]
    name = "Alexander Bartels"
    description = "swproxy is a library to write service workers with ease."
    website = "http://swproxy.alexanderbartels.com"
    twitter = "https://twitter.com/bartelsxander"
    github = "https://github.com/alexanderbartels/swproxy"
    copyrightyear = "2015"
    google_analytics = "UA-54367902-1"
